In [2]:
import numpy as np 
import pandas as pd

Object Creation

In [4]:
#series
s=pd.Series([1,2,3,np.nan,5,6])
print(s)

0    1.0
1    2.0
2    3.0
3    NaN
4    5.0
5    6.0
dtype: float64

In [10]:
#dataframe
dates=pd.date_range("20260101",periods=6)
print(dates)
df=pd.DataFrame(np.random.randn(6,4),index=dates,columns=["A","B","C","D"])
print(df)

DatetimeIndex(['2026-01-01', '2026-01-02', '2026-01-03', '2026-01-04',
               '2026-01-05', '2026-01-06'],
              dtype='datetime64[us]', freq='D')
                   A         B         C         D
2026-01-01  0.348249  1.472440 -0.038010 -0.306090
2026-01-02 -0.213345  0.376263 -0.155014  0.352186
2026-01-03 -0.124254  0.095561  0.233795 -1.983044
2026-01-04 -1.759647 -0.019457 -0.779033 -2.204321
2026-01-05 -1.010525 -0.069044  0.435134 -0.749326
2026-01-06 -1.609268  0.520967  0.702160  0.067761

In [18]:
df2=pd.DataFrame(
    {
        "A":np.arange(0,10),
        "B":pd.date_range('20260101',periods=10),
        "C":pd.Series(1,index=list(range(10)),dtype="float32"),
        "D":np.array([3]*10,dtype="int32"),
        "E":pd.Categorical(["test1","test2","test3","test4","test5","test6","test7","train1","train2","train3"]),
        "F":list("ABCDEFGIUN")
    }
)
df2

   A          B    C  D       E  F
0  0 2026-01-01  1.0  3   test1  A
1  1 2026-01-02  1.0  3   test2  B
2  2 2026-01-03  1.0  3   test3  C
3  3 2026-01-04  1.0  3   test4  D
4  4 2026-01-05  1.0  3   test5  E
5  5 2026-01-06  1.0  3   test6  F
6  6 2026-01-07  1.0  3   test7  G
7  7 2026-01-08  1.0  3  train1  I
8  8 2026-01-09  1.0  3  train2  U
9  9 2026-01-10  1.0  3  train3  N

In [23]:
#to view top or bottoom of dataframe
df2.head()
df2.tail(2)

   A          B    C  D       E  F
8  8 2026-01-09  1.0  3  train2  U
9  9 2026-01-10  1.0  3  train3  N

In [26]:
df.index
df.columns

Index(['A', 'B', 'C', 'D'], dtype='str')

In [29]:
#convert to numpy()
df.to_numpy()

array([[ 0.34824858,  1.47244037, -0.03800988, -0.30608972],
       [-0.21334508,  0.37626327, -0.155014  ,  0.35218643],
       [-0.12425389,  0.09556073,  0.23379461, -1.98304394],
       [-1.75964736, -0.01945697, -0.77903262, -2.20432114],
       [-1.01052466, -0.06904403,  0.43513387, -0.74932615],
       [-1.60926791,  0.52096693,  0.70215973,  0.06776094]])

In [31]:
df.describe()

              A         B         C         D
count  6.000000  6.000000  6.000000  6.000000
mean  -0.728132  0.396122  0.066505 -0.803806
std    0.861213  0.575129  0.518239  1.067584
min   -1.759647 -0.069044 -0.779033 -2.204321
25%   -1.459582  0.009297 -0.125763 -1.674614
50%   -0.611935  0.235912  0.097892 -0.527708
75%   -0.146527  0.484791  0.384799 -0.025702
max    0.348249  1.472440  0.702160  0.352186

In [35]:
#sorting
df.sort_index(axis=1,ascending=False)
df.sort_values(by='B')

                   A         B         C         D
2026-01-05 -1.010525 -0.069044  0.435134 -0.749326
2026-01-04 -1.759647 -0.019457 -0.779033 -2.204321
2026-01-03 -0.124254  0.095561  0.233795 -1.983044
2026-01-02 -0.213345  0.376263 -0.155014  0.352186
2026-01-06 -1.609268  0.520967  0.702160  0.067761
2026-01-01  0.348249  1.472440 -0.038010 -0.306090